repos:
  # Formatters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  # Linters
  - repo: https://github.com/rhysd/actionlint
    rev: "v1.6.25"
    hooks:
      - id: actionlint
